# Fedora Dockerfile

FROM fedora

# python must be referred to as python3, and pip is not installed.
RUN yum -y install python3-pip

COPY app /app

WORKDIR /app

# installs the requirements.
RUN pip install -r requirements.txt

# I thought I could run this, but it bombs.
# python3 -m unittest Tests/*
